[package]
name = "stdio-mask"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.158"
nix = { version = "0.29.0", features = ["term", "process", "ioctl", "fs", "signal"] }
serde = { version = "1.0.208", features = ["derive"] }
toml = "0.8.19"
